apiVersion: v1
kind: Pod
metadata:
  labels:
    run: vault-watcher
  name: vault-watcher
spec:
  containers:
  - image: vikash32/vault-watcher:0.1
    name: vault-watcher
    resources: {}
    env:
    - name: VAULT_ADDR
      value: "http://vault-standby.vault.svc.cluster.local:8200"
    - name: VAULT_TOKEN
      value: "hvs.u1dKEP759W3O5aYM73sBbroR"
    - name: SECRET_PATH
      value: "/v1/secret/data/myfirstsecret/path/ui"
    - name: NAMESPACE
      value: "default"
    - name: DEPLOYMENT_NAME
      value: "nginx-with-secret"
    - name: SECRET_NAME
      value: "my-secret"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
